" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

set encoding=utf-8
scriptencoding=utf-8

" Set <space> as the leader key
let mapleader = " "

"
" vim-plug - Vim plugin manager
"
runtime plugin.vim
" vim-plug sets automatically the following settings:
" set filetype plugin indent on
" syntax enable

"""
""" Configuration: non plugin settings
"""

" When editing a file, always jump to the last known cursor position.
" Don't do it for commit messages, when the position is invalid, or when
" inside an event handler (happens when dropping a file on gvim).
autocmd BufReadPost *
  \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

" turn off modelines in files - security
set modelines=0

" have at least 3 lines during scolling
set scrolloff=3

" motion with backspace between lines
set backspace=indent,eol,start

" show line numers left (with minimum size)
set number
set numberwidth=5

" highlight current line
set cursorline

" better command-line completion
" disable: using plugin wilder.nvim
"set wildmenu

" ignore file patterns
set wildignore+=*/tmp/*,*/.direnv/*
set wildignore+=*.swp,*.bak,*~
set wildignore+=*.zip,*.tgz,*.tar.gz
set wildignore+=*.o,*.a,*.so
set wildignore+=*.aux,*.bbl,*.blg,*.hsh,*.log,*.nav,*.out,*.snm,*.toc,*.upa,*.vrb,*.vtc
set wildignore+=*.pdf

" better ignorecase search
set ignorecase
set smartcase

" enable leaving modified buffers
set hidden

" show partial commands in the last line of the screen
set showcmd

" highlight searches (use <C-L> to turn off highlighting)
set hlsearch

" highlight during typing a search string
set incsearch

" use one space, not two, after punctuation when joining lines
set nojoinspaces

" use system clipboard
set clipboard=unnamedplus
set mouse=a
noremap x "_x
noremap X "_x

" set the characters for the list view
" → u2192, ↲ u21b2, · u00b7, ␣ u2423, ☐ u2610
" space has been added since patch-7.4.710
if has("patch-7.4.710")
  set listchars=tab:→\ ,eol:↲,space:·,nbsp:␣,trail:☐
else
  set listchars=tab:→\ ,eol:↲
endif

" syntax highlighting for ~/.ssh/config.d/*
au BufNewFile,BufRead ~/.ssh/config.d/*  setf sshconfig

" syntax highlighting for *.rasi files (e.g. rofi config)
au BufNewFile,BufRead /*.rasi  setf css

"
" securing gopass
"
au BufNewFile,BufRead /dev/shm/gopass.* setlocal noswapfile nobackup noundofile

"
" Spell Checking and Word Completion
"

" Spell-check language
set spelllang=en_us

"
" Turn on spellchecking the ftplugin/filetype.vim file
"
" autocmd FileType filetype setlocal spell

" Set spellfile to location that is guaranteed to exist,
" can be symlinked to Dropbox or kept in Git
" and managed outside of thoughtbot/dotfiles using rcm.
set spellfile=$HOME/.vim/spell-en.utf-8.add

" Autocomplete with dictionary words when spell check is on
set complete+=kspell

" Enable project specifix .vimrc files (secured)
set exrc
set secure

" Key mappings
runtime mapping.vim

" For abbreviations read in the following file:
runtime abbrev.vim

""" end of ~/.vimrc
