#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/asmvik/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
# yabai -m config                                 \
#     external_bar                 off:40:0       \
#     menubar_opacity              1.0            \
#     mouse_follows_focus          off            \
#     focus_follows_mouse          off            \
#     display_arrangement_order    default        \
#     window_origin_display        default        \
#     window_placement             second_child   \
#     window_insertion_point       focused        \
#     window_zoom_persist          on             \
#     window_shadow                on             \
#     window_animation_duration    0.0            \
#     window_animation_easing      ease_out_circ  \
#     window_opacity_duration      0.0            \
#     active_window_opacity        1.0            \
#     normal_window_opacity        0.90           \
#     window_opacity               off            \
#     insert_feedback_color        0xffd75f5f     \
#     split_ratio                  0.50           \
#     split_type                   auto           \
#     auto_balance                 off            \
#     top_padding                  12             \
#     bottom_padding               12             \
#     left_padding                 12             \
#     right_padding                12             \
#     window_gap                   06             \
#     layout                       bsp            \
#     mouse_modifier               fn             \
#     mouse_action1                move           \
#     mouse_action2                resize         \
#     mouse_drop_action            swap

#
# System settings
#
# `Settings` > `Accessibility` > `Motion` > enable `Reduce motion`
#
# `Settings` > `Desktop & Dock` > under `Mission Control`
#   disable everything except `Displays have separate Spaces`

yabai -m config layout         bsp

yabai -m config left_padding   6
yabai -m config right_padding  6
yabai -m config top_padding    6
yabai -m config bottom_padding 6
yabai -m config window_gap     6

yabai -m config window_placement second_child

# mouse settings
yabai -m config mouse_follows_focus on

# press alt to modifiy mouse button behavior
yabai -m config mouse_modifier alt
# alt + left click + drag
yabai -m config mouse_action1 move
# alt + right click + drag
yabai -m config mouse_action2 resize

yabai -m config mouse_drop_action swap

# ignore the following Apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off

yabai -m rule --add app="^KeePassXC$" manage=off
yabai -m rule --add app="^Nextcloud$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Cisco Secure Client$" manage=off
yabai -m rule --add app="^DFN VoIP-Centrex$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off

echo "yabai configuration loaded.."
