#!/usr/bin/perl

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

die unless defined($acpi);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;

if ($status eq 'Discharging') {
	$full_text = '';
} elsif ($status eq 'Charging') {
	$full_text = '⚡';
}

if ($percent < 10) {
	$full_text .= ' ';
} elsif ($percent < 20) {
	$full_text .= ' ';
} elsif ($percent < 55) {
	$full_text .= ' ';
} elsif ($percent < 80) {
	$full_text .= ' ';
} else {
	$full_text .= ' ';
}

$full_text .= " $percent%";

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " $1";
}

# print text
print "$full_text\n";
print "$full_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

	if ($percent < 20) {
		print "#dc322f\n";
	} elsif ($percent < 40) {
		print "#dc322f\n";
	} elsif ($percent < 80) {
		print "#859900\n";
	} else {
	}

	if ($percent < 5) {
		exit(33);
	}
} else {
	print "#859900\n";
}

exit(0);
